version: "3.8"

services:
  app:
    build:
      context: .
      target: builder
    container_name: cms-mcp-server-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/cms-mcp
      - SCHEDULER_INTERVAL=60000
    depends_on:
      - mongo
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
    command: node --no-warnings=ExperimentalWarning --loader ts-node/esm/transpile-only src/index.ts

  mongo:
    image: mongo:6
    container_name: cms-mcp-mongo-dev
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
