version: "3.8"

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: cms-mcp-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/cms-mcp
      - TWITTER_USERNAME=${TWITTER_USERNAME:-}
      - TWITTER_PASSWORD=${TWITTER_PASSWORD:-}
      - TWITTER_EMAIL=${TWITTER_EMAIL:-}
      - TWITTER_2FA_SECRET=${TWITTER_2FA_SECRET:-}
    depends_on:
      - mongo
    stdin_open: true # Keep stdin open for MCP Stdio transport
    tty: true # Allocate a pseudo-TTY

  # You can include mongo here if you want to run it standalone
  # Or reference the mongo service from the main docker-compose network
  mongo:
    image: mongo:6
    container_name: cms-mcp-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
